name: Proxy-Status Error Type Registration Request
description: 'Request a new Proxy-Status error type.'
title: 'Registration Request: [ your parameter name ]'
labels: new registration
body:
      - type: markdown
        attributes:
          value: |
            Please confirm that:
            - You have read and understood the [registration process](https://www.rfc-editor.org/rfc/rfc9209.html#name-defining-new-proxy-error-ty).
            - You have checked [the registry](https://www.iana.org/assignments/http-proxy-status/http-proxy-status.xhtml#http-proxy-error-types) and found no current values that meet your needs.
            - If you have a specification reference, its URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC).
      - type: input
        id: name
        attributes:
          label: Name
          description: The error type name; must conform to the constraints in the RFC.
        validations:
          required: true
      - type: input
        id: description
        attributes:
          label: Description
          description: A description of the conditions that generate the proxy error type.
        validations:
          required: true
      - type: input
        id: extra
        attributes:
          label: Extra Parameters
          description: Zero or more optional parameters, along with their allowable Structured Type(s)
        validations:
          required: false
      - type: input
        id: status_code
        attributes:
          label: Recommended HTTP Status Code
          description: The appropriate HTTP status code for this entry.
        validations:
          required: true
      - type: dropdown
        id: intermediary_generated
        attributes:
          label: Response Only Generated by Intermediaries
          options:
            - This proxy error type can only be generated by an intermediary
            - This proxy error type can be generated by intermediaries and origin servers, or just origin servers.
        validations:
          required: true
      - type: input
        id: reference
        attributes:
          label: Reference
          description: A URL referring to the parameter's specification document.
        validations:
          required: false
      - type: textarea
        id: additional_info
        attributes:
          label: Additional Information
          description: Is there any additional information we should know? This will not be included in the registry.
