name: Proxy-Status Parameter Registration Request
description: 'Request a new Proxy-Status parameter.'
title: 'Registration Request: [ your parameter name ]'
labels: new registration
body:
      - type: markdown
        attributes:
          value: |
            Please confirm that:
            - You have read and understood the [registration process](https://www.rfc-editor.org/rfc/rfc9209.html#name-defining-new-proxy-status-p).
            - You have checked [the registry](https://www.iana.org/assignments/http-proxy-status/http-proxy-status.xhtml#http-proxy-status-parameters) and found no current values that meet your needs.
            - If you have a specification reference, its URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC).
      - type: input
        id: name
        attributes:
          label: Name
          description: The parameter name; must conform to the constraints in the RFC.
        validations:
          required: true
      - type: input
        id: description
        attributes:
          label: Description
          description: A description of the parameter; see the registry for examples.
        validations:
          required: true
      - type: input
        id: reference
        attributes:
          label: Reference
          description: A URL referring to the parameter's specification document.
        validations:
          required: false
      - type: textarea
        id: additional_info
        attributes:
          label: Additional Information
          description: Is there any additional information we should know? This will not be included in the registry.
